// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkild6xN6sRz4yUbQWwXn4pTLxwuRgRQ',
    appId: '1:282785449148:web:fe32cb38303d640898fcb9',
    messagingSenderId: '282785449148',
    projectId: 'restaurant-developer',
    authDomain: 'restaurant-developer.firebaseapp.com',
    storageBucket: 'restaurant-developer.appspot.com',
    measurementId: 'G-H34TM8YSBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz_UR1Q72YJ7My3GMht_S6cdJWHQHYuCQ',
    appId: '1:282785449148:android:7487133fc42abd8d98fcb9',
    messagingSenderId: '282785449148',
    projectId: 'restaurant-developer',
    storageBucket: 'restaurant-developer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACwejGlSoAQYjFfO5-qKIe78Prd9ovASc',
    appId: '1:282785449148:ios:b324f71dbf59a81798fcb9',
    messagingSenderId: '282785449148',
    projectId: 'restaurant-developer',
    storageBucket: 'restaurant-developer.appspot.com',
    iosClientId: '282785449148-tpvtah7enm52gm5i50knt1tje1ca1b3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttermvvmtemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACwejGlSoAQYjFfO5-qKIe78Prd9ovASc',
    appId: '1:282785449148:ios:b324f71dbf59a81798fcb9',
    messagingSenderId: '282785449148',
    projectId: 'restaurant-developer',
    storageBucket: 'restaurant-developer.appspot.com',
    iosClientId: '282785449148-tpvtah7enm52gm5i50knt1tje1ca1b3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttermvvmtemplate',
  );
}
